version: '3.8'
services:
  backend:
    build: ../backend
    ports:
      - "8000:8000"
    env_file:
      - ../.env.example
    volumes:
      - ../backend:/app
  frontend:
    build: ../frontend
    ports:
      - "3000:80"
    env_file:
      - ../.env.example
    volumes:
      - ../frontend:/app
    depends_on:
      - backend